module "my_network" {
 source = "./network"
 VPC_CIDR= var.VPC_CIDR
 COMPANY_NAME = var.COMPANY_NAME
 PUBLIC_SUBNET_1_CIDR= var.PUBLIC_SUBNET_1_CIDR
 PUBLIC_SUBNET_2_CIDR =var.PUBLIC_SUBNET_2_CIDR
 PRIVATE_SUBNET_1_CIDR = var.PRIVATE_SUBNET_1_CIDR
 PRIVATE_SUBNET_2_CIDR = var.PRIVATE_SUBNET_2_CIDR
 AZ_1 = var.AZ_1
 AZ_2 = var.AZ_2
 REGION = var.REGION
 ALL_ROUTE_IP4 = var.ALL_ROUTE_IP4
 ALL_ROUTE_IP6 = var.ALL_ROUTE_IP6
 SSH_PORT  = var.SSH_PORT
 PORT = var.PORT
}